checkpoint_dir: ""
data_parallel: 1

sense:
  calib_width: 32
  device: 3
  crop: 0.70
  kernel_width: 6

data:
  num_coils: 8
  channels: 16
  path: "/storage/fastMRI_brain/data"
  num_of_top_slices: 8
  resolution: 384

optimizer:
  lr: 0.001
  beta_1: 0
  beta_2: 0.99

train:
  batch_size: 10
  n_epochs: 100
  P: 2
  adv_weight: 0.01
  l1_weight: 1
  num_iters_discriminator: 1
  gp_weight: 10
  drift_weight: 0.001

validate:
  batch_size: 40
  mu_std: 0.01
  psnr_threshold: 0.25
  P: 8
  cfid_P: 8

test:
  batch_size: 40
  P: 32
  cfid_P: 8
